[project]
name = "clp"
version = "0.1.0"
description = "A simple command-line audio player."
readme = "README.md"
authors = [
    { name = "David Shaw", email = "dshaw1@dstl.gov.uk" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
clp = "clp.cli:main"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.12.0",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]

[tool.ruff]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
